---
editor_options: 
  markdown: 
    wrap: sentence
---

# Introduction {#intro}

Lovelace and Dumont, define spatial microsimulation along two predominant paradigms, as a technique or an approach [@Lovelace2018]. The former being a method through which spatial microdata is generated, that is, individual level data are allocated to geographical zones. This can be achieved by the combination of individual and geographically aggregated data. In this respect, spatial microsimulation can be thought of as population synthesis [@Axhausen2011]. In contrast, microsimulation from an approach point of view, refers to understanding phenomena based on spatial microdata, particularly multi-level phenomena. Due to the creation of synthetic data, microsimulation can be an adequate solution when data availability is limited. Spatial microsimulation seeks to merge the advantages of individual level data with the geographical specificity of geographical data. Although it may seem like microsimulation achieves the best of both worlds of individual and geographical data, there are some key assumptions that underpin spatial microsimulation models and should therefore be considered when thinking about adopting microsimulation [@Lovelace2014 ; @Lovelace2018].
The first assumption refers to the extent to which the microdata is representative of the area being studied.
Another assumption that spatial microsimulation makes, is the relationship and interactions between the target variable and its dependency on the constraint variable.
In particular, it assumes that the interactions do not fluctuate across space and time.
Furthermore, another key assumption is that there is no spatial dependency of the relationship between the constraint variables.
Finally, the fourth assumption is that the constraints and micro/individual level data contain an adequate level of detail, such that they can reproduce the diversity of individuals in the study area.
This report engages with microsimulation as a technique, to allocate individual level data to geographical zones.
In specific, using microsimulation to estimate a population-level dataset of holiday-making behaviours at the household level in Leeds.
The individual-level dataset is of a survey describing holiday making behaviours of individuals.
In contrast, the constraints data are from the 2011 Census and represent the output area classification in Leeds.
These data are then used and applied using microsimulation to obtain a population- level dataset of holiday making behaviours at the household level in Leeds.
3 The scope of this report is to focus on destinations classified as city holidays, specifically city destinations in the United States.
The aim is to profile consumers holidaying to these destinations, in order to underpin a targeted marketing campaign.
The report is structured as follows: Section 2 will explore the data and methods used, taking into account the scope of the study.
Section 3 will focus on profiling the target market.
Finally, section 4 will conclude, synthesising over the findings and establishing the customers to be targeted with a marketing campaign.
