# Conclusion

This report is based on data that was generated using microsimulation, to develop a population-level dataset of holidaymaking behaviours at the household level in Leeds. Some of the underlying assumptions of this method were disclaimed in the introduction, such as the extent of representativeness of the survey/individual level data to the population as a whole. In the following section, data and methods, the data was described and the degree of oversampling as a result of the underlying assumptions was explored. Particularly, the microsimulation oversampling seems to occur in the output areas in the city centre area and its immediate surroundings. Similarly in this section the different destinations according to holiday type were demonstrated, to show where the locations of interest (Orlando & Las Vegas) were ranked relative to other city locations. Once the target locations were identified, in the results section, a unique consumer profile was developed, along 5 main demographic variables/characteristics: age band, household income, number of children, and satisfaction with most recent holiday and Supergroup name. Furthermore, age band, overall satisfaction, suburbanites, and have children, were identified as the characteristics of interest in terms of the geographic distribution of individuals having all these attributes. As figure 4.2 demonstrates these individuals are towards the peripheries of the study area, a key aspect to consider when deciding the spatial element of a targeted marketing strategy. A key assumption made here is the variables of interest, in other words, figure 4.2 only shows individuals that meet all the specified criteria in relation to the specified variables, however it may be the case that the marketing efforts want to be concentrated on individuals having only a subset of the specified variables, for example: suburbanites and children. However, the developed results were generated with specificity in mind, i.e. the more specific the demographics of the target market the better the foundation from which the targeted marketing strategy could be developed. Nevertheless, although the combination of demographics was defined in this case, a separate combination of variables can be developed upon upper management's request, thereby altering the geographical distribution of the target market. All in all, the target market can be defined as young professionals aged between 35 to 49, with children, enjoy a relatively high income (41-50K), and prefer beach holiday/were not satisfied with their most recent city holiday. Given this information, a suitable marketing strategy would be to market beach holidays as opposed to city holidays to this demographic (given their lack of satisfaction).

## Future directions

This report lays the foundation for future exploration into city destinations. In specific, future analysis may focus on aggregating the category, for instance, developing a consumer profile of the individuals holidaying to all city estimations and comparing them to the population as a whole. With regards to the extent to which the microsimulation data oversampled, if the resources were allocable the simulation could be rerun, using other constraint variables to generate the data, in this case the constraints were oac_group and age_sex. The results can then be compared to see how this influences the extent of oversampling. Furthermore, different weighting strategies for developing the microsimulated data can be tested, establishing which algorithms are most efficient for spatial microsimulation.
