--- 
title: "Predictive Analytics Techniques- Spatial Microsimulation"
author: "Nils Indreiten"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is an assignment completed for the GEOG5042M Predictive Analytics module, part of the MSc Consumer Analytics and Marketing Strategy, Jan 2021 - Jan 2022 cohort."
---
```{r setup, include=FALSE}
pacman::p_load(tidyverse,sf, grid, grid,gridExtra, GGally,kableExtra, knitr)
load("weights_oac_age_sex.rda")
load("Microsimulated_data.rda")
load("Props_function.rda")
oa_boundaries <- st_read("./data/oa_boundaries.geojson", crs=27700)
ward_boundaries <- st_read("./data/ward_boundaries.geojson", crs=27700)
```
# Executive Summary

This report engages with data analysis on a microsimulated dataset, that estimates a population-level dataset of holiday-making behaviours at the household level in Leeds. The aim is to profile consumers holidaying to city locations in the United States. In the introduction the scope is set out, along with a disclaimer of the underlying assumptions of microsimulated data. In Section 2 Data and Methods, an overview of the data is provided, the underlying assumptions of the microsimulated data are explored, and finally the data are inspected given the scope of the report. The following section, presents the results and profiles the holidaymaker according to a set of variables, such as age, income, etc. In addition, the geographic distribution of the target market is presented. Finally, in the final section concludes the report, providing some ideas as to how the findings might underpin a targeted marketing campaign and future directions are suggested.